services:
  db:
    image: postgres:14
    container_name: postgresql_db
    restart: always
    environment:
      POSTGRES_DB: projectdb
      POSTGRES_USER: kristiyanpisev
      POSTGRES_PASSWORD: djangoproject01022025
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: kristiyanpisev@admin.com
      PGADMIN_DEFAULT_PASSWORD: djangoprojectadmin
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:
