services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: KrisP03
      POSTGRES_PASSWORD: KrisDB_003
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: kristiyanpisev@gmail.com
      PGADMIN_DEFAULT_PASSWORD: KrisDB_003
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  postgres_data:
  pgadmin_data: